[[pages]]
path = "pages/1_Setup.py"
name = "Setup Page"
icon = "âš™ï¸"

[[pages]]
path = "pages/2_Market Overview.py"
name = "Market Overview"
icon = "ğŸŒ"

[[pages]]
path = "pages/3_Google.py"
name = "Google"
icon = "ğŸ”"