[[pages]]
path = "pages/1_Setup.py"
name = "Setup Page"
icon = "âš™ï¸"

[[pages]]
path = "pages/2_Market Overview.py"
name = "Market Overview"
icon = "ğŸŒ"

[[pages]]
path = "pages/3_Google.py"
name = "Google"
icon = "ğŸ”"

[[pages]]
path = "pages/4_PMAX.py"
name = "PMAX Categeory Analysis"
icon = "ğŸ”"

[[pages]]
path = "pages/5_Meta.py"
name = "Meta"
icon = "ğŸ™‹â€â™‚ï¸"

[[pages]]
path = "pages/6_Tiktok.py"
name = "Tiktok"
icon = "ğŸ“¹"

[[pages]]
path = "pages/7_Snapchat.py"
name = "Snapchat"
icon = "ğŸ“·"